name: expense_tracker
description: A Flutter application for tracking expenses.
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.4
  firebase_core: ^2.25.4
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
flutter:
  uses-material-design: true